language: ruby

rvm:
  - 2.4.0

cache: bundler

sudo: required

env:
  - RAILS_ENV=test

matrix:
  fast_finish: true

services:
  - mysql

addons:
  apt:
    packages:
      - imagemagick libmagickwand-dev

before_install:
  - bash .travis.install-mysql-5.7
  - gem update --system 2.6.11
  - gem install bundler -v 1.14.6

before_script:
  - cp .travis.database.yml config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate