language: ruby

rvm:
  - 2.4.0

cache: bundler

sudo: required

env:
  - RAILS_ENV=test

matrix:
  fast_finish: true

services:
  - mysql

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - imagemagick libmagickwand-dev
      - cmake
      - cmake-data

before_install:
  - bash .travis.install-mysql-5.7
  - gem update --system 2.6.11
  - gem install bundler -v 1.14.6

before_script:
  - cp .travis.database.yml config/database.yml

script:
  - export RAILS_ENV=test
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:seed
  - bundle exec ./rspec-in-order

notifications:
  email:
    recipients:
      - b.g.dariush@gmail.com