language: ruby

rvm:
  - 2.4.0

cache: bundler

sudo: required

env:
  - RAILS_ENV=test

matrix:
  fast_finish: true

before_install:
  - gem update --system 2.6.11
  - gem update bundler

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

addons:
  apt:
    packages:
      - imagemagick libmagickwand-dev

before_script:
  - cp .travis.database.yml config/database.yml