defaults: &defaults
  domain: www.viramobl.com
  protocol: http
    
  currency: تومان
  
  passwords:
    reset:
      expiration: 24.hours
      token_length: 5
    two_step_auth:
      token_length: 6
      send_expiration: 10.minutes
      confirmed_expiration: 30.minutes
    
  sms_api:
    sms_ir:
      username: <%= ENV['SMS_API_USERNAME'] %>
      password: <%= ENV['SMS_API_PASSWORD'] %>
      
  recaptcha:
    verify: https://www.google.com/recaptcha/api/siteverify
    keys:
      site: <%= ENV['RECAPTCHA_SITE_KEY'] || '' %>
      secret: <%= ENV['RECAPTCHA_SECRET_KEY'] || '' %>
      
  preference:
    timing:
      sms: [9, 21]

development:
  <<: *defaults
  domain: dev.viramobl.com

test:
  <<: *defaults
  domain: dev.viramobl.com

production:
  <<: *defaults
  protocol: https
  