defaults: &defaults
  brand: مبل ویرا
  domain: www.viramobl.com
  protocol: http

  currency: تومان

  passwords:
    reset:
      expiration: 24.hours
      token_length: 5
    two_step_auth:
      token_length: 6
      send_expiration: 10.minutes
      confirmed_expiration: 30.minutes

  nextpay:
    api_key: 9ade3494-bc47-49a6-a13e-08914d699704
    curl_uri: https://api.nextpay.org/gateway/token.http
    soap_uri: https://api.nextpay.org/gateway/token.wsdl
    payment_uri: https://api.nextpay.org/gateway/payment
    callback_uri: /payment/callback

  sms_api:
    sms_ir:
      username: <%= ENV['SMS_API_USERNAME'] %>
      password: <%= ENV['SMS_API_PASSWORD'] %>

  recaptcha:
    verify: https://www.google.com/recaptcha/api/siteverify
    keys:
      site: <%= ENV['RECAPTCHA_SITE_KEY'] || '' %>
      secret: <%= ENV['RECAPTCHA_SECRET_KEY'] || '' %>

  session:
    expiration: 60.minutes

  preference:
    price:
      round: 5000
      added_value_factor: 0.09
      transit:
        compute_method: max
    furniture:
      unit: 7
    sms:
      outdated: 24.hours
      timing: [9, 21]

  fabric:
    colours:
      cluster:
        k: 24
        runs: 50
        colour_sampling: [3, 3]

  notifications:
    prefered: telegram
    telegram:
      chat_id: 87186355
      order_notifications:
        token: 442229527:AAFbAxNiGbCxjlz0dspfMIpnlwUDzBzySdQ
      admin_notifications:
        token: 435215235:AAFaWZHZTzQ2QxuLqQTFQdU67nt4K2T0FsE

development:
  <<: *defaults
  domain: localhost:3000

test:
  <<: *defaults
  domain: localhost:3000

production:
  <<: *defaults
  protocol: https
