defaults: &defaults
  domain: www.viramobl.com
    
  currency: تومان
  
  passwords:
    reset_expiration: 24.hours
    reset_token_length: 5
    
  sms_api:
    sms_ir:
      username: <%= ENV['SMS_API_USERNAME'] %>
      password: <%= ENV['SMS_API_PASSWORD'] %>
  
  css:
    furniture:
      cover:
        height: 500
        height_unit: px

development:
  <<: *defaults
  domain: dev.viramobl.com

test:
  <<: *defaults
  domain: dev.viramobl.com

production:
  <<: *defaults
  